upgrade of android-tools to 10.0.0.r36
kraj/meta-clang pull request #495
Opened 2021-08-08 21:36 UTC by nishaparakkat

An older version is present in the meta-oe layer.
Took the old recipe and adapted it in the following way:

--Deleted all the old patches that were applicable for
old version.

--Used all the makefiles that come with the new version
directly from the source code, just modifying them
to install output to a specific folder as below

a)added rules_yocto.mk that will mimic the debian/rules
b)modified the makefiles of the components to output to
a common dir.
c)
Built boringssl crypto with the option -DOPENSSL_NO_ASM
to solve the below errors

 libcrypto.so.0: undefined reference to `aes_hw_encrypt'
 libcrypto.so.0: undefined reference to `aes_hw_set_encrypt_key'
 libcrypto.so.0: undefined reference to `gcm_gmult_v8'
 libcrypto.so.0: undefined reference to `gcm_init_v8'
 libcrypto.so.0: undefined reference to `sha256_block_data_order'
 libcrypto.so.0: undefined reference to `aes_hw_ctr32_encrypt_blocks'
 libcrypto.so.0: undefined reference to `aes_hw_cbc_encrypt'
 libcrypto.so.0: undefined reference to `vpaes_decrypt'
 libcrypto.so.0: undefined reference to `vpaes_encrypt'
 libcrypto.so.0: undefined reference to `gcm_gmult_neon'
 libcrypto.so.0: undefined reference to `sha1_block_data_order'
 libcrypto.so.0: undefined reference to `sha512_block_data_order'
 libcrypto.so.0: undefined reference to `gcm_init_neon'
 libcrypto.so.0: undefined reference to `aes_hw_set_decrypt_key'
 libcrypto.so.0: undefined reference to `vpaes_set_decrypt_key'
 libcrypto.so.0: undefined reference to `gcm_ghash_neon'
 libcrypto.so.0: undefined reference to `bn_mul_mont'
 libcrypto.so.0: undefined reference to `aes_hw_decrypt'
 libcrypto.so.0: undefined reference to `gcm_ghash_v8'
 libcrypto.so.0: undefined reference to `vpaes_cbc_encrypt'
 libcrypto.so.0: undefined reference to `ChaCha20_ctr32'
 libcrypto.so.0: undefined reference to `vpaes_ctr32_encrypt_blocks'
 libcrypto.so.0: undefined reference to `vpaes_set_encrypt_key'

 Attention : https://github.com/grpc/grpc/issues/9440

d) compiled android compatible version of libunwind to be used
to build libbacktrace
e) REQUIRES meta-selinux for libselinux, thus added it to
BBFILES_DYNAMIC of this layer.
f) checked compilation and packaging for for x86_64 and aarch64
g) UNTESTED android-tools-adbd.service , couldn't find how to build adbd
that is needed by the service with the new version of android-tools. At
present the service is still packaged but may not work.
h) tested the adb and fastboot on the core-image-minimal by including
the android-tools in the image and ran the commands with 'help'

Signed-off-by: Nisha Parrakat <Nisha.Parrakat@kpit.com>
Signed-off-by: Nisha Parrakat <nishaparrakat@gmail.com>

---
### Contributor checklist

- [ ] Changes have been tested
- [ ] `Signed-off-by` is present
- [ ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

2021-08-09 17:55 UTC, kraj requested changes
I think this patch is more applicable to meta-oe, is there anything clang specifc ?

2021-08-09 18:40 UTC, nishaparakkat commented
hi Khem, the new version of android-tools uses clang toolchain to build the libraries. Without the clang toolchain, its not trivial to build android-tools latest version as per the debian makefiles present. The old version can be used as it is by people who do not want clang dependency.

2021-08-10 17:03 UTC, kraj commented
> hi Khem, the new version of android-tools uses clang toolchain to build the libraries. Without the clang toolchain, its not trivial to build android-tools latest version as per the debian makefiles present. The old version can be used as it is by people who do not want clang dependency.

ok makes sense.

2021-08-12 17:08 UTC, merged

2021-08-12 18:10 UTC, nishaparakkat commented
Thanks Khem!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Khem Raj ***@***.***>
Sent: Thursday, August 12, 2021 7:08:27 PM
To: kraj/meta-clang ***@***.***>
Cc: Nisha Parrakat ***@***.***>; Author ***@***.***>
Subject: Re: [kraj/meta-clang] upgrade of android-tools to 10.0.0.r36 (#495)

Caution: This email originated from outside of the KPIT. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Merged #495<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkraj%2Fmeta-clang%2Fpull%2F495&data=04%7C01%7Cnisha.parrakat%40kpit.com%7C5295c2d6eda94003245a08d95db3ce77%7C3539451eb46e4a26a242ff61502855c7%7C0%7C0%7C637643849179382391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BvxF9HmtPavICaTXKKW%2FueDMhKbypeXnTrq78beQw%2BM%3D&reserved=0> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkraj%2Fmeta-clang%2Fpull%2F495%23event-5150927532&data=04%7C01%7Cnisha.parrakat%40kpit.com%7C5295c2d6eda94003245a08d95db3ce77%7C3539451eb46e4a26a242ff61502855c7%7C0%7C0%7C637643849179392350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8ILWCbXPVS%2FeylEQxF5CCoa8gHIWw2%2FHnQ91biSTlDI%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH53ZHXT66XDLXLRYAL74BLT4P5YXANCNFSM5BY4GWUA&data=04%7C01%7Cnisha.parrakat%40kpit.com%7C5295c2d6eda94003245a08d95db3ce77%7C3539451eb46e4a26a242ff61502855c7%7C0%7C0%7C637643849179392350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MyyLfjhVm7RmoOODrgcbtizPWPzby0ZmkXD4BbWGVwM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnisha.parrakat%40kpit.com%7C5295c2d6eda94003245a08d95db3ce77%7C3539451eb46e4a26a242ff61502855c7%7C0%7C0%7C637643849179392350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g1Y6yq4gG%2BNyo9o0dprH%2FbaJaTgraVF88zRAZJUBBUQ%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cnisha.parrakat%40kpit.com%7C5295c2d6eda94003245a08d95db3ce77%7C3539451eb46e4a26a242ff61502855c7%7C0%7C0%7C637643849179402307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=72ldx7Fr4YMD5rlYom9sZnmcsClzHJxSIIu5HCBSOY0%3D&reserved=0>.

This message contains information that may be privileged or confidential and is the property of the KPIT Technologies Ltd. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message. KPIT Technologies Ltd. does not accept any liability for virus infected mails.