objcopy: fix path for RISC-V
kraj/meta-clang pull request #698
Opened 2022-12-02 15:09 UTC by pyih

Make path to OBJCOPY correct for linux-yocto package. Use gcc for now for erlang and pciutils.

Signed-off-by: Alexey Smirnov <pyih.soft@gmail.com>

---
### Contributor checklist

- [x] Changes have been tested
- [x] `Signed-off-by` is present
- [x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

2022-12-04 01:16 UTC, kraj requested changes

2022-12-04 01:16 UTC, kraj commented on conf/nonclangable.conf
> +TOOLCHAIN:pn-pciutils:riscv64 = "gcc"
we have clang-15 in master, does this happen with clang-15 too ?

2022-12-04 01:16 UTC, kraj commented on conf/nonclangable.conf
> +TOOLCHAIN:pn-u-boot = "gcc"
this change I have in a different review too https://github.com/kraj/meta-clang/pull/697

2022-12-05 08:05 UTC, pyih commented
Okay, I'll remove this PR, migrate to llvm 15, and re-check.

2022-12-05 08:05 UTC, closed without merging