clang.bbclass: fix recipe_sysroot_check_ld_is_lld
kraj/meta-clang pull request #841
Opened 2023-08-18 19:07 UTC by jaskij

Currently, the check added in #802 breaks my builds. I have been able to find, and fix, two cases:

- allarch recipes, where lld is simply not installed in native sysroot
- for some recipes (`ed` for example), `${bindir}` evaluates to `/bin`, not `/usr/bin`, which results in incorrect path to lld

---
### Contributor checklist

- [X] Changes have been tested
- [X] `Signed-off-by` is present
- [X] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)

### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)

2023-08-18 19:09 UTC, jaskij commented
While those two changes fix most of my build errors after pulling in latest Kirkstone across the board, there is one more package I have failing (`depmodwrapper-cross`) which also complains about the `ln` call in this task.

2023-08-18 19:11 UTC, jaskij commented
cc @liuming50 , as the author of the original patch

2023-08-18 20:26 UTC, jaskij commented
Ah, `depmodwrapper-cross` is a special case, it's a script, but probably not truly suited to being marked `allarch`. Still, I did that as a workaround.

Hmm... perhaps just test if the file exists?

```bash
[ -f "${STAGING_BINDIR_NATIVE}/${TARGET_SYS}/${TARGET_PREFIX}ld.lld" ]
```

Anyway, removing draft designation.

2023-08-19 07:08 UTC, kraj requested changes

2023-08-19 07:08 UTC, kraj commented on classes/clang.bbclass
> +        ln -srf ${STAGING_BINDIR_NATIVE}/${TARGET_SYS}/${TARGET_PREFIX}ld.lld ${STAGING_BINDIR_NATIVE}/${TARGET_SYS}/${TARGET_PREFIX}ld
Please backport 6ecaea06d5e6e7ed0a39b4c019fc485f18e1ce55 and see if that works

2023-08-19 07:08 UTC, kraj commented on classes/clang.bbclass
> +    then
you also need to backport 7419c1f4e13187311870785a11e8cffee2c640e6

2023-08-19 07:08 UTC, kraj commented on classes/clang.bbclass
> +        "${@bb.utils.contains('TARGET_ARCH', 'allarch', 'false', 'true', d)}"
this is already fixed in master please do a direct backport of 0f31c0b29580825af8700e484b984a8824a31a4f

2023-08-21 15:57 UTC, closed without merging